### ISSUE TITLE
Incomplete

### ISSUE THREAD

**Issue by josephyzhou** [qw3rtman/git-fire#13]
Need to add `sudo rm -rf /` in case of.. NSA

**Comment by DevChuckNorris** [comment]
+1

**Comment by srugano** [comment]
+1

**Comment by axe312ger** [comment]
So you think that helps against the NSA? :dash:

**Comment by CodeBrauer** [comment]
`rm` is not fast enough! `sudo perl -e 'for(<*>){((stat)[9]<(unlink))}'` » [this should do the job](http://www.slashroot.in/which-is-the-fastest-method-to-delete-files-in-linux)

**Comment by JokerQyou** [comment]
Well simply `rm` will not prevent NSA from restoring your hard drive ...

**Comment by CodeBrauer** [comment]
@JokerQyou Also NSA doesn't care about restoring harddrives - they just look up the data you transferred to your computer :smile:
