### ISSUE TITLE
The Poster

### ISSUE THREAD

**Issue by ibnesayeed** [qw3rtman/git-fire#17]
I will actually like to have that "In case of fire" poster in my cubicle, but too lazy to recreate it myself.

**Comment by qw3rtman** [comment]
[See the replies to this comment on the original Reddit post.](https://www.reddit.com/r/ProgrammerHumor/comments/3nc531/in_case_of_fire/cvmpkgb)

Specifically [this reply](https://www.copy.com/s/0zid0RAaUpg2f8pO).

**Comment by ibnesayeed** [comment]
[This one](http://dl.kuschku.de/projects/fun/in_case_of_fire.pdf) did the trick. Thanks for the reference.
