### ISSUE TITLE
Consider force pushing the branch to ensure work ends up at the remote

### ISSUE THREAD

**Issue by steadweb** [qw3rtman/git-fire#21]
Hooks could prevent the code from being pushed. In the state of an emergency I'd want my code to be pushed, regardless.

**Comment by glensc** [comment]
or just disable hooks:

git-push(1):

>   --[no-]verify
>   Toggle the pre-push hook (see githooks(5)).
> The default is --verify, giving the hook a chance to prevent the push. With --no-verify, the hook is bypassed completely.
