### ISSUE TITLE
Multiple remotes fail to push to either of them

### ISSUE THREAD

**Issue by joseprl89** [qw3rtman/git-fire#22]
Output from command:

Switched to a new branch 'fire-develop-josep.rodriguez@tigerspike.com-1465578516'
[fire-develop-josep.rodriguez@tigerspike.com-1465578516 9cc522d] @a
 1 file changed, 176 deletions(-)
 delete mode 100644 app/build.gradle
**fatal: 'Client
origin' does not appear to be a git repository**
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Leave building!

**Comment by qw3rtman** [comment]
Are you having this issue when you `git push` normally?

Based on the error (`fatal: 'Client origin' does not appear to be a git repository`) it looks like the remote repository isn't set up correctly.

**Comment by joseprl89** [comment]
It does work for both of them.

I reckon the issue is the script uses a variant of "git remotes" to identify the name of the origin to push to, and since there's to it uses a string that maps to "origin_1**\n**origin2"

**Comment by afdev82** [comment]
The version in the npm has this issue, the one in the github master doesn't.
The fix is in this commit https://github.com/qw3rtman/git-fire/commit/ec70c998a0a4fb50bc83e431938b9328bdf10dcd , but the file in the npm didn't get updated.

**Comment by qw3rtman** [comment]
`npm` has been updated! Sorry for the confusion, @joseprl89.
