### ISSUE TITLE
.bat version for Windows?

### ISSUE THREAD

**Issue by Vortigern-The-Grey** [qw3rtman/git-fire#48]
What if there was a version that was a .bat script for Windows? You could get the email, repo name and branch name from git, etc.
EDIT: I have made a rough conversion of git-fire to python, but will keep this windows open, as it doesn't have some of the same functionality.

**Comment by glensc** [comment]
You forgot to share link of that python port

**Comment by Vortigern-The-Grey** [comment]
Here you are! [https://github.com/Vortigern-The-Grey/gitfire-py](https://github.com/Vortigern-The-Grey/gitfire-py)
