### ISSUE TITLE
Npm module

### ISSUE THREAD

**Issue by akashnimare** [qw3rtman/git-fire#6]
Npm module would be a great option. Shelljs anyone?

**Comment by akashnimare** [comment]
BTW I have made the basic module for this.
https://github.com/akashnimare/gitfire

**Comment by qw3rtman** [comment]
[Published to NPM](https://npmjs.com/git-fire).

Install with `npm install -g git-fire`, which will simply copy the `git-fire` binary to your `$PATH`.

See c653c56.

**Comment by akashnimare** [comment]
Awesome. I didn't knew that.
